theme: jekyll-theme-modernist
title: 统数视界
description: > # this means to ignore newlines until "baseurl:"
  微信搜索“统数视界”，关注公众号。
logo: wx.jpg
github: 'https://mathicu.github.io/index'
markdown: kramdown
show_downloads: true
github:
  home_url: https://mathicu.github.io/
  zip_url: https://mathicu.github.io/wjf
  tar_url: https://mathicu.github.io/xxds
  repository_url: https://mathicu.github.io/gltj


  